name: Format

on:
  pull_request:
    types:
      - opened

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check code formatting
        run: npx prettier . --check
